name: Makefile BatallaDigital CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Instalación valgrind
      run: sudo apt install -y valgrind

    - name: Compilación del juego
      run: cd TP2 && make batalla_digitalv2

    - name: Comprobar memoria
      run: cd TP2 && make leak_test
