name: Makefile BatallaDigital CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make Batalla Digital
      run: cd TP2 && make batalla_digitalv2

    - name: Comprobar memoria
      run: make leak_test
